# build futelasterisk server Debian 9
Vagrant.configure("2") do |config|
	config.vm.define "dev"
	# NOTE: contrib has host vbox tools installed
  config.vm.box = "debian/contrib-stretch64"
	config.vm.synced_folder ".", "/shared",
		:mount_options => ["dmode=777,fmode=777"]
	
	config.vm.provision "dev", type: "ansible" do |ansible|
		ansible.playbook = "dev.yml"
	end

	config.vm.provider :virtualbox do |vb|
		config.vm.network "private_network", type: "dhcp", :adapter => 2
	end
end
